# If a branch is deleted, this will remove its deployment files

name: Clean Branches

on:
  delete:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          ref: gh-pages
      - name: Delete
        run: |
          git fetch
          for folder in `\ls .`; do 
            echo $folder
            if [ ! `git rev-parse --verify origin/$folder 2>/dev/null` ]; then 
              echo "Deleting $folder..."
              rm -rf $folder
            else
              echo "Keeping $folder..."
            fi
          done
        

