# TODO: this won't work, because the release thing
# has to bundle a JRE, and running on Linux would
# cause it to bundle a linux JRE. Oops!
name: Post New Release

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Release Title'
        required: true
        type: string
      body:
        description: 'Release Body'
        required: true
        type: string
      tag:
        description: 'Release Tag'
        required: true
        type: string

jobs:
  make-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stable
      - name: Set up JDK 17
        uses: oracle-actions/setup-java@v1.1.3
        with:
          release: '17'

      - name: Build with Maven
        run: JAVA_HOME=$JAVA_HOME_17_X64 mvn -T3 clean install

      - name: Copy artifacts
        run: cp

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.title }}
          body: ${{ inputs.body }}
          tag_name: ${{ inputs.tag }}
          files: |
            triggevent-linux.zip
            triggevent-win-bjoy.zip
            triggevent-win.zip

